### ISSUE TITLE
Recommendation: use scoped imports or import lists

### ISSUE THREAD

**Issue by mattfenwick** [jayunit100/rudolf_web#1]
Instead of:

```
(ns rudolfweb.actions
  (:use hiccup.core) 
  (:use hiccup.form-helpers))
```

Use 

```
(ns rudolfweb.actions
  (:use [hiccup.core :only (func1 func2)]) 
  (:use [hiccup.form-helpers :only (f1 f2)]))
```

Or 

```
(ns rudolfweb.actions
  (:use [hiccup.core :as hc]) 
  (:require [hiccup.form-helpers :as hfh]))
```

Problem:  a bare `:use` puts all symbols directly in the current namespace.  Names may clash, it's very hard to figure out where symbols are coming from.  And it's hard to understand code.

Solutions: 
1. add `:only` to give explicit list of imported symbols
2. harness `:require` to refer to symbols by a namespace prefix

**Comment by jayunit100** [comment]
Yes -- this should be done in blogtemplate.clj and actions.clj (and possibly other files, too).
